In [1]:
import sys
sys.path.insert(0,'/Users/alexandra/Documents/master_thesis')

"""
Magic commands
"""

%load_ext autoreload
%autoreload 2

"""
Load relevant packages
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

import pandas_datareader as pdr
from pandas_datareader.yahoo.daily import YahooDailyReader


import datetime

"""
Load own functions/packages
"""

# set plotting style

from codelib.visualization.layout import DefaultStyle
DefaultStyle();

In [2]:
'''Import ticker list'''

etf_list = pd.read_csv("/Users/alexandra/Documents/master_thesis/sb_etfs.csv")

etf_list

    Ticker
0     SPDV
1     SDOG
2     VALQ
3     BFOR
4     ESGS
..     ...
238    EES
239   DGRS
240    DTD
241   QARP
242   DEUS

[243 rows x 1 columns]

In [30]:
"""
Get adjusted stock prices for SB ETFs.
"""

tickers = list(etf_list['Ticker'])
etfs=[]
for ticker in tickers:
    etf = YahooDailyReader(ticker, start=datetime.date(2002, 12, 1),interval='d').read()
    etfs.append(etf)

In [33]:
etfs

[                 High        Low       Open      Close   Volume  Adj Close
 Date
 2017-11-29  25.309999  25.059999  25.059999  25.299999   1100.0  22.078945
 2017-11-30  25.559999  25.299999  25.299999  25.559999   2700.0  22.305841
 2017-12-01  25.520000  25.250000  25.520000  25.250000    500.0  22.035307
 2017-12-04  25.719999  25.719999  25.719999  25.719999    200.0  22.445465
 2017-12-05  25.559999  25.559999  25.559999  25.559999    200.0  22.305841
 ...               ...        ...        ...        ...      ...        ...
 2022-03-04  31.540001  31.070000  31.540001  31.424000   8300.0  31.424000
 2022-03-07  31.360001  30.969000  31.250000  30.993000  10000.0  30.993000
 2022-03-08  31.410000  30.806999  31.160000  30.806999  23300.0  30.806999
 2022-03-09  31.320000  31.049999  31.049999  31.084000   5800.0  31.084000
 2022-03-10  31.059999  30.728001  31.059999  30.976000  11100.0  30.976000

 [1077 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2012-07-16  25.660000  25.490000  25.660000  25.620001   19600.0  18.373135
 2012-07-17  25.889999  25.520000  25.830000  25.870001  316800.0  18.552418
 2012-07-18  26.049999  25.809999  25.920000  26.030001   39900.0  18.667164
 2012-07-19  26.100000  26.000000  26.100000  26.070000   23000.0  18.695847
 2012-07-20  25.959999  25.830000  25.920000  25.860001   24600.0  18.545242
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  54.799999  54.130001  54.320000  54.799999   41800.0  54.799999
 2022-03-07  54.770000  53.959999  54.770000  54.029999   36100.0  54.029999
 2022-03-08  54.820000  53.790001  54.330002  53.790001  153900.0  53.790001
 2022-03-09  54.630001  54.090000  54.410000  54.090000   86700.0  54.090000
 2022-03-10  54.099998  53.599998  53.720001  54.060001   27400.0  54.060001

 [2430 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2018-01-16  40.799999  40.549000  40.759998  40.549000    2600.0  37.473354
 2018-01-17  41.060001  40.779999  40.790001  41.060001  147100.0  37.945595
 2018-01-18  41.049999  40.930000  40.959999  40.930000    5200.0  37.825455
 2018-01-19  41.040001  41.026001  41.040001  41.026001     500.0  37.914173
 2018-01-22  41.290001  41.290001  41.290001  41.290001     500.0  38.158142
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  51.369999  50.891998  50.891998  51.363998    2600.0  51.363998
 2022-03-07  51.180000  50.330002  51.150002  50.330002    5600.0  50.330002
 2022-03-08  50.650002  50.060001  50.340000  50.060001   22900.0  50.060001
 2022-03-09  50.939999  50.450001  50.450001  50.570000    5500.0  50.570000
 2022-03-10  50.520000  50.125000  50.419998  50.520000   13600.0  50.520000

 [1046 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2013-06-04  25.110001  24.799999  25.100000  24.879999   59500.0  23.495314
 2013-06-05  25.070000  24.559999  25.070000  24.600000   19400.0  23.230898
 2013-06-06  24.740000  24.500000  24.740000  24.680000   31800.0  23.306444
 2013-06-07  25.320000  24.879999  25.320000  25.059999   26300.0  23.665297
 2013-06-10  26.260000  25.010000  25.600000  25.120001  582800.0  23.721956
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  58.110001  57.840000  58.060001  58.110001    2700.0  58.110001
 2022-03-07  57.900002  56.160000  57.900002  56.160000     600.0  56.160000
 2022-03-08  56.919998  55.919998  56.020000  56.130001   10300.0  56.130001
 2022-03-09  57.580002  57.400002  57.400002  57.580002     900.0  57.580002
 2022-03-10  57.490002  56.709999  56.779999  57.490002    5100.0  57.490002

 [2209 rows x 6 columns],
                  High        Low       Open      Close  Volume  Adj Close
 Date
 2016-07-20  25.780001  25.780001  25.780001  25.780001     0.0  19.644144
 2016-07-21  25.750000  25.750000  25.750000  25.750000  6600.0  19.621283
 2016-07-22  25.750000  25.750000  25.750000  25.750000     0.0  19.621283
 2016-07-25  25.740000  25.719999  25.740000  25.719999   500.0  19.598429
 2016-07-26  25.719999  25.719999  25.719999  25.719999     0.0  19.598429
 ...               ...        ...        ...        ...     ...        ...
 2022-03-04  38.509998  38.340000  38.462002  38.509998  2000.0  38.509998
 2022-03-07  38.209999  37.860001  38.112000  37.900002  4100.0  37.900002
 2022-03-08  37.680000  37.587002  37.680000  37.587002   400.0  37.587002
 2022-03-09  38.115002  37.971001  38.115002  37.971001   200.0  37.971001
 2022-03-10  37.841999  37.830002  37.830002  37.841999   200.0  37.841999

 [1421 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2012-03-21  20.070000  19.934999  19.955000  20.014999  123200.0  18.416351
 2012-03-22  19.955000  19.940001  19.940001  19.940001    1200.0  18.347347
 2012-03-23  19.920000  19.785000  19.785000  19.920000    8400.0  18.328938
 2012-03-26  20.230000  20.070000  20.070000  20.219999    2000.0  18.604975
 2012-03-27  20.260000  20.190001  20.260000  20.190001    4000.0  18.577377
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  74.099998  72.879997  73.989998  73.360001  387000.0  73.360001
 2022-03-07  73.410004  70.779999  73.400002  70.889999   70900.0  70.889999
 2022-03-08  72.339996  69.910004  70.620003  70.519997   68300.0  70.519997
 2022-03-09  73.000000  71.940002  72.089996  72.709999   51900.0  72.709999
 2022-03-10  71.910004  70.889999  71.589996  71.709999   31100.0  71.709999

 [2510 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2018-10-24  26.040001  24.510000  24.980000  24.510000  184200.0  23.843899
 2018-10-25  24.760000  24.500000  24.500000  24.650000   33800.0  23.980091
 2018-10-26  24.570000  24.170000  24.370001  24.260000   16400.0  23.600695
 2018-10-29  24.629999  23.950001  24.549999  23.950001  119000.0  23.299118
 2018-10-30  24.469999  24.420000  24.420000  24.450001     500.0  23.785532
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  44.160000  43.660000  44.119999  44.080002   63000.0  44.080002
 2022-03-07  44.090000  42.810001  44.090000  42.840000  160000.0  42.840000
 2022-03-08  43.490002  42.450001  42.799999  42.450001  131300.0  42.450001
 2022-03-09  43.540001  43.180000  43.220001  43.340000  137500.0  43.340000
 2022-03-10  43.299999  42.740002  43.099998  43.200001   79000.0  43.200001

 [850 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-09-15  25.299999  25.020000  25.145000  25.250000  15600.0  21.828112
 2016-09-16  25.370001  25.084999  25.370001  25.180000  14900.0  21.767599
 2016-09-19  25.350000  25.170000  25.209999  25.219999  18300.0  21.802177
 2016-09-20  28.600000  25.150000  25.240000  26.920000  52200.0  23.271791
 2016-09-21  25.459999  25.150000  25.270000  25.459999  59900.0  22.009653
 ...               ...        ...        ...        ...      ...        ...
 2022-03-04  43.439999  43.000000  43.259998  43.349998  56900.0  43.349998
 2022-03-07  43.330002  42.310001  43.330002  42.360001  67800.0  42.360001
 2022-03-08  43.055000  42.080002  42.349998  42.130001  58100.0  42.130001
 2022-03-09  43.169998  42.830002  42.930000  42.950001  53200.0  42.950001
 2022-03-10  42.770000  42.284000  42.360001  42.660000  57900.0  42.660000

 [1381 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2016-09-15  25.160000  24.865000  24.940001  25.150000    8800.0  20.973637
 2016-09-16  25.040001  24.870001  25.040001  24.995001    5700.0  20.844379
 2016-09-19  25.230000  25.080000  25.090000  25.120001   15700.0  20.948624
 2016-09-20  25.200001  25.059999  25.200001  25.059999    8600.0  20.898584
 2016-09-21  25.309999  25.070000  25.250000  25.280001    6000.0  21.082048
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  40.169998  39.689999  39.910000  40.169998  114700.0  40.169998
 2022-03-07  40.060001  39.320000  40.060001  39.349998  279600.0  39.349998
 2022-03-08  39.924000  39.150002  39.419998  39.209999  207300.0  39.209999
 2022-03-09  40.110001  39.680000  39.830002  39.799999  214300.0  39.799999
 2022-03-10  39.889999  39.395000  39.450001  39.700001  169400.0  39.700001

 [1381 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2016-09-15  25.129999  24.860001  24.870001  25.100000   14400.0  23.195707
 2016-09-16  24.992001  24.900000  24.990000  24.992001    2500.0  23.095894
 2016-09-19  25.125000  24.969999  25.080000  25.020000   10000.0  23.121777
 2016-09-20  25.299999  25.062000  25.299999  25.062000    7700.0  23.160585
 2016-09-21  25.299999  25.020000  25.160000  25.270000    6800.0  23.352808
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  48.529999  47.950001  48.130001  48.520000   86700.0  48.520000
 2022-03-07  48.360001  47.500000  48.360001  47.500000   32200.0  47.500000
 2022-03-08  47.750000  46.755001  47.419998  46.790001  109400.0  46.790001
 2022-03-09  47.812000  47.355000  47.369999  47.590000  249600.0  47.590000
 2022-03-10  47.639999  47.070000  47.259998  47.540001  280200.0  47.540001

 [1381 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-09-15  25.200001  24.860001  24.955000  25.180000   6200.0  23.883371
 2016-09-16  25.110001  25.010000  25.038000  25.049999  11500.0  23.760061
 2016-09-19  25.280001  25.160000  25.170000  25.165001   5500.0  23.869144
 2016-09-20  25.250000  25.150000  25.246000  25.150000   6500.0  23.854916
 2016-09-21  25.462000  25.145000  25.230000  25.462000  15200.0  24.150845
 ...               ...        ...        ...        ...      ...        ...
 2022-03-04  48.259998  47.719002  48.259998  48.198002  14600.0  48.198002
 2022-03-07  48.250000  46.490002  48.250000  46.490002  45000.0  46.490002
 2022-03-08  47.240002  46.040001  46.439999  46.271000  22200.0  46.271000
 2022-03-09  47.869999  47.150002  47.169998  47.615002  19700.0  47.615002
 2022-03-10  47.540001  46.830002  46.990002  47.450001  39100.0  47.450001

 [1381 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-09-16  25.205000  25.120001  25.180000  25.205000   5200.0  23.321964
 2016-09-19  25.370001  25.230000  25.320000  25.260000   8400.0  23.372856
 2016-09-20  25.510000  25.295000  25.510000  25.299999   7400.0  23.409868
 2016-09-21  25.549999  25.260000  25.400000  25.549999  10500.0  23.641190
 2016-09-22  25.860001  25.680000  25.860001  25.740000  10900.0  23.816998
 ...               ...        ...        ...        ...      ...        ...
 2022-03-04  50.660000  50.129002  50.459999  50.580002  47300.0  50.580002
 2022-03-07  50.580002  49.080002  50.580002  49.080002  94400.0  49.080002
 2022-03-08  49.830002  48.500000  49.080002  48.580002  84200.0  48.580002
 2022-03-09  50.108002  49.500000  49.500000  49.880001  38900.0  49.880001
 2022-03-10  49.619999  49.020000  49.279999  49.500000  62800.0  49.500000

 [1380 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2016-09-15  25.270000  24.940001  25.000000  25.260000    4200.0  23.153608
 2016-09-16  25.139999  25.049999  25.129999  25.049999    6000.0  22.961123
 2016-09-19  25.299999  25.120001  25.250000  25.129999   11700.0  23.034452
 2016-09-20  25.219999  25.100000  25.173000  25.150000    9500.0  23.052778
 2016-09-21  25.290001  25.100000  25.260000  25.290001   36800.0  23.181110
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  49.500000  48.919998  49.310001  49.330002   72700.0  49.330002
 2022-03-07  49.349998  47.779999  49.349998  47.860001  160400.0  47.860001
 2022-03-08  48.709999  47.439999  47.880001  47.490002  115900.0  47.490002
 2022-03-09  48.910000  48.279999  48.529999  48.730000  104300.0  48.730000
 2022-03-10  48.689999  48.049999  48.160000  48.549999  145900.0  48.549999

 [1381 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2006-07-11  19.940001  19.700001  19.799999  19.940001  248300.0  15.995017
 2006-07-12  19.889999  19.709999  19.889999  19.709999   11900.0  15.810512
 2006-07-13  19.660000  19.400000  19.660000  19.410000   13500.0  15.569877
 2006-07-14  19.540001  19.309999  19.540001  19.440001   19200.0  15.593936
 2006-07-17  19.360001  19.260000  19.360001  19.260000    3600.0  15.449546
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  76.800003  75.599998  75.910004  76.709999  328600.0  76.709999
 2022-03-07  76.510002  75.050003  76.510002  75.059998  542600.0  75.059998
 2022-03-08  75.419998  73.540001  74.930000  73.540001  660000.0  73.540001
 2022-03-09  75.320000  74.550003  74.870003  74.900002  454100.0  74.900002
 2022-03-10  74.589996  73.660004  74.040001  74.489998  299400.0  74.489998

 [3945 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2007-05-10  20.070000  20.030001  20.070000  20.040001    3000.0  17.973356
 2007-05-11  20.040001  20.040001  20.040001  20.040001       0.0  17.973356
 2007-05-14  20.040001  20.040001  20.040001  20.040001       0.0  17.973356
 2007-05-15  19.799999  19.799999  19.799999  19.799999     200.0  17.758110
 2007-05-16  19.799999  19.799999  19.799999  19.799999       0.0  17.758110
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  55.750000  54.279999  55.750000  54.790001  120900.0  54.790001
 2022-03-07  54.639999  51.709999  54.599998  51.730000  109700.0  51.730000
 2022-03-08  53.880001  51.639999  51.900002  52.419998  247200.0  52.419998
 2022-03-09  54.500000  53.740002  53.779999  53.880001  446500.0  53.880001
 2022-03-10  53.830002  52.919998  53.160000  53.779999  246200.0  53.779999

 [3736 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2007-05-10  19.840000  19.809999  19.830000  19.809999    3200.0  16.145836
 2007-05-11  19.780001  19.740000  19.740000  19.780001   10000.0  16.121389
 2007-05-14  19.820000  19.820000  19.820000  19.820000   12000.0  16.153992
 2007-05-15  19.780001  19.719999  19.780001  19.780001   11500.0  16.121389
 2007-05-16  19.780001  19.760000  19.780001  19.760000   11000.0  16.105087
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  63.520000  62.720001  63.040001  63.410000   29600.0  63.410000
 2022-03-07  63.830002  62.340000  63.439999  62.380001  135400.0  62.380001
 2022-03-08  62.570000  60.840000  62.419998  60.880001  114500.0  60.880001
 2022-03-09  61.900002  61.360001  61.779999  61.490002   78800.0  61.490002
 2022-03-10  61.450001  60.650002  61.029999  61.259998   72800.0  61.259998

 [3736 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2017-01-04  24.061001  24.061001  24.061001  24.061001    600.0  23.150574
 2017-01-05  24.061001  24.061001  24.061001  24.061001      0.0  23.150574
 2017-01-06  24.061001  24.061001  24.061001  24.061001      0.0  23.150574
 2017-01-09  24.061001  24.061001  24.061001  24.061001      0.0  23.150574
 2017-01-10  24.061001  24.061001  24.061001  24.061001      0.0  23.150574
 ...               ...        ...        ...        ...      ...        ...
 2022-03-04  31.933001  31.931000  31.933001  31.931000    400.0  31.931000
 2022-03-07  31.309000  31.080000  31.250000  31.080000   2700.0  31.080000
 2022-03-08  31.108999  30.756001  30.870001  30.756001    600.0  30.756001
 2022-03-09  31.677999  31.520000  31.531000  31.539000  24700.0  31.539000
 2022-03-10  31.443001  31.118999  31.118999  31.443001   1900.0  31.443001

 [1305 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-03-18  20.120001  20.080000  20.090000  20.090000  12300.0  19.517954
 2016-03-21  20.090000  20.090000  20.090000  20.090000      0.0  19.517954
 2016-03-22  20.129999  20.049999  20.100000  20.100000  14800.0  19.527668
 2016-03-23  20.070000  20.037001  20.070000  20.037001  39100.0  19.466461
 2016-03-24  20.030001  19.959999  19.980000  20.030001  75600.0  19.459661
 ...               ...        ...        ...        ...      ...        ...
 2022-03-04  36.320000  35.889999  36.110001  36.220001   9800.0  36.220001
 2022-03-07  36.189999  35.169998  36.189999  35.169998   4600.0  35.169998
 2022-03-08  35.876999  35.180000  35.189999  35.340000   7000.0  35.340000
 2022-03-09  36.040001  35.750000  35.840000  35.799999  35800.0  35.799999
 2022-03-10  36.000000  35.509998  35.769001  35.959999   5100.0  35.959999

 [1506 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2014-03-06  20.129999  19.864000  20.090000  19.864000  926500.0  19.328671
 2014-03-07  20.090000  19.700001  20.090000  19.860001  499400.0  19.324780
 2014-03-10  19.860001  19.680000  19.860001  19.820000  222000.0  19.285854
 2014-03-11  20.490000  19.620001  20.490000  19.670000  306800.0  19.139898
 2014-03-12  19.740000  19.490000  19.639999  19.690001  162000.0  19.159353
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  47.430000  46.717999  47.200001  47.279999  100000.0  47.279999
 2022-03-07  47.430000  45.639999  47.430000  45.639999  236900.0  45.639999
 2022-03-08  46.810001  45.779999  45.959999  45.869999  150300.0  45.869999
 2022-03-09  46.910000  46.251999  46.430000  46.779999  471400.0  46.779999
 2022-03-10  46.950001  46.209999  46.320000  46.849998  517100.0  46.849998

 [2019 rows x 6 columns],
                  High        Low       Open      Close  Volume  Adj Close
 Date
 2018-10-18  19.000000  18.290001  19.000000  18.350000  4600.0  17.618414
 2018-10-19  18.420000  18.280001  18.420000  18.280001  3600.0  17.551207
 2018-10-22  18.170000  18.129999  18.170000  18.129999  2100.0  17.407188
 2018-10-23  17.860001  17.610001  17.840000  17.860001  1000.0  17.147955
 2018-10-24  17.530001  17.500000  17.530001  17.520000   900.0  16.821508
 ...               ...        ...        ...        ...     ...        ...
 2022-03-04  24.950001  24.809999  24.940001  24.830000  3200.0  24.830000
 2022-03-07  24.450001  24.049999  24.450001  24.180000  1600.0  24.180000
 2022-03-08  24.200001  24.049999  24.200001  24.049999  1000.0  24.049999
 2022-03-09  24.610001  24.549999  24.580000  24.610001  1100.0  24.610001
 2022-03-10  24.790001  24.590000  24.590000  24.790001   600.0  24.790001

 [854 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2017-08-09  19.959999  19.920000  19.920000  19.930000   10400.0  18.486469
 2017-08-10  19.830000  19.830000  19.830000  19.830000     300.0  18.393715
 2017-08-11  19.870001  19.796000  19.870001  19.796000    3000.0  18.362175
 2017-08-14  19.940001  19.940001  19.940001  19.940001     200.0  18.495743
 2017-08-15  19.940001  19.889999  19.889999  19.940001     300.0  18.495743
 ...               ...        ...        ...        ...       ...        ...
 2022-03-04  30.290001  30.000999  30.090000  30.270000   32400.0  30.270000
 2022-03-07  30.120001  29.650000  30.120001  29.650000   38500.0  29.650000
 2022-03-08  30.170000  29.473000  29.709999  29.528000   14000.0  29.528000
 2022-03-09  30.180000  29.969999  29.997999  30.000000  547900.0  30.000000
 2022-03-10  29.930000  29.662001  29.745001  29.885000   16900.0  29.885000

 [1155 rows x 6 columns],

In [50]:
etf_prices=pd.concat([etf.iloc[:,-1] for etf in etfs],axis=1)

In [51]:
etf_prices.columns=tickers
etf_prices

,SPDV,SDOG,VALQ,BFOR,ESGS,QQQE,DSTL,FDRR,FDVV,FDLO,...,DON,EZM,USMF,DGRW,DES,EES,DGRS,DTD,QARP,DEUS
Date,,,,,,,,,,,,,,,,,,,,,
2002-12-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-04,31.424000,54.799999,51.363998,58.110001,38.509998,73.360001,44.080002,43.349998,40.169998,48.520000,...,43.639999,53.540001,40.175999,62.419998,31.830000,47.799999,44.619999,63.270000,40.487000,44.534000
2022-03-07,30.993000,54.029999,50.330002,56.160000,37.900002,70.889999,42.840000,42.360001,39.349998,47.500000,...,42.310001,51.610001,39.189999,60.869999,31.139999,46.509998,43.720001,62.049999,39.469002,43.314999
2022-03-08,30.806999,53.790001,50.060001,56.130001,37.587002,70.519997,42.450001,42.130001,39.209999,46.790001,...,42.139999,51.680000,38.828999,60.130001,31.080000,46.570000,43.759998,61.500000,39.146000,43.048000
2022-03-09,31.084000,54.090000,50.570000,57.580002,37.971001,72.709999,43.340000,42.950001,39.799999,47.590000,...,42.869999,53.060001,39.500000,61.150002,31.469999,47.560001,44.320000,62.290001,39.969002,43.998001
2022-03-10,30.976000,54.060001,50.520000,57.490002,37.841999,71.709999,43.200001,42.660000,39.700001,47.540001,...,42.910000,53.119999,39.431000,60.779999,31.530001,47.509998,44.259998,62.230000,39.914001,43.852001

In [52]:
'''Resampling monthly prices'''
etf_prices = etf_prices.resample('BM').last()
etf_prices=etf_prices[0:-3]
etf_prices

,SPDV,SDOG,VALQ,BFOR,ESGS,QQQE,DSTL,FDRR,FDVV,FDLO,...,DON,EZM,USMF,DGRW,DES,EES,DGRS,DTD,QARP,DEUS
Date,,,,,,,,,,,,,,,,,,,,,
2002-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,30.285000,52.980000,51.844002,61.090000,36.875000,87.190002,43.009998,43.340000,38.699001,49.959999,...,42.810001,53.889999,40.779999,62.360001,31.900000,49.299999,46.029999,61.625000,41.849998,46.328999
2021-09-30,29.620001,51.090000,48.967999,58.950001,35.596001,82.879997,40.959999,41.380001,37.000000,47.520000,...,41.450001,52.009998,38.924000,58.840000,30.830000,48.330002,44.369999,58.709999,39.641998,44.102001
2021-10-29,29.870001,52.150002,50.485001,62.709999,37.068001,87.300003,43.340000,43.452999,38.959999,50.540001,...,43.250000,54.279999,40.536999,62.299999,31.910000,50.200001,45.869999,61.930000,42.027000,46.681999
2021-11-30,28.905001,50.450001,49.960999,62.459999,35.896000,85.900002,42.689999,42.840000,38.299999,49.544998,...,42.220001,53.279999,39.423000,61.849998,31.230000,49.759998,45.110001,60.994999,41.807999,45.650002
2021-12-31,30.931999,53.590000,52.938999,64.440002,38.199001,85.309998,46.279999,45.369999,40.299999,52.313999,...,44.360001,56.279999,41.971001,65.860001,32.860001,51.400002,47.599998,64.739998,43.898998,48.320000

In [54]:
'''Save adjusted close prices'''
etf_prices.to_csv("/Users/alexandra/Documents/master_thesis/etfs_prices.csv")