In [2]:
import sys
sys.path.insert(0,'/Users/alexandra/Documents/master_thesis')

"""
Magic commands
"""

%load_ext autoreload
%autoreload 2

"""
Load relevant packages
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

import pandas_datareader as pdr
from pandas_datareader.yahoo.daily import YahooDailyReader


import datetime

"""
Load own functions/packages
"""

# set plotting style

from codelib.visualization.layout import DefaultStyle
DefaultStyle();

In [5]:
'''Import ticker list'''

etf_list = pd.read_csv("/Users/alexandra/Documents/master_thesis/data/sb_etfs.csv")

etf_list

    Ticker
0     SPDV
1     SDOG
2     VALQ
3     BFOR
4     ESGS
..     ...
238    EES
239   DGRS
240    DTD
241   QARP
242   DEUS

[243 rows x 1 columns]

In [6]:
"""
Get adjusted stock prices for SB ETFs.
"""

tickers = list(etf_list['Ticker'])
etfs=[]
for ticker in tickers:
    etf = YahooDailyReader(ticker, start=datetime.date(2002, 12, 1),interval='d').read()
    etfs.append(etf)

In [7]:
etfs

[                 High        Low       Open      Close   Volume  Adj Close
 Date
 2017-11-29  25.309999  25.059999  25.059999  25.299999   1100.0  21.666975
 2017-11-30  25.559999  25.299999  25.299999  25.559999   2700.0  21.889645
 2017-12-01  25.520000  25.250000  25.520000  25.250000    500.0  21.624165
 2017-12-04  25.719999  25.719999  25.719999  25.719999    200.0  22.026676
 2017-12-05  25.559999  25.559999  25.559999  25.559999    200.0  21.889645
 ...               ...        ...        ...        ...      ...        ...
 2022-03-23  31.760000  31.502001  31.760000  31.502001  20300.0  31.502001
 2022-03-24  31.774000  31.610001  31.760000  31.730000  18700.0  31.730000
 2022-03-25  32.200001  32.028000  32.044998  32.200001   1600.0  32.200001
 2022-03-28  32.180000  31.830000  32.180000  31.962000   2600.0  31.962000
 2022-03-29  32.198101  31.959999  32.014999  32.198101   5374.0  32.198101

 [1090 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2012-07-16  25.660000  25.490000  25.660000  25.620001   19600.0  17.843454
 2012-07-17  25.889999  25.520000  25.830000  25.870001  316800.0  18.017572
 2012-07-18  26.049999  25.809999  25.920000  26.030001   39900.0  18.129005
 2012-07-19  26.100000  26.000000  26.100000  26.070000   23000.0  18.156868
 2012-07-20  25.959999  25.830000  25.920000  25.860001   24600.0  18.010607
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  55.430000  54.900002  55.430000  54.900002  156900.0  54.365002
 2022-03-24  54.950001  54.500000  54.650002  54.930000   32400.0  54.930000
 2022-03-25  55.660000  54.939999  55.020000  55.650002   33900.0  55.650002
 2022-03-28  55.490002  54.919998  55.490002  55.349998   52800.0  55.349998
 2022-03-29  55.840000  55.462002  55.459999  55.810001   47863.0  55.810001

 [2443 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2018-01-16  40.799999  40.549000  40.759998  40.549000    2600.0  37.126835
 2018-01-17  41.060001  40.779999  40.790001  41.060001  147100.0  37.594704
 2018-01-18  41.049999  40.930000  40.959999  40.930000    5200.0  37.475670
 2018-01-19  41.040001  41.026001  41.040001  41.026001     500.0  37.563568
 2018-01-22  41.290001  41.290001  41.290001  41.290001     500.0  37.805286
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  51.880001  51.380001  51.880001  51.380001    2700.0  51.380001
 2022-03-24  52.020000  51.599998  51.700001  52.020000   25400.0  52.020000
 2022-03-25  52.500000  52.220001  52.220001  52.500000   12800.0  52.500000
 2022-03-28  52.509998  52.080002  52.509998  52.419998    3600.0  52.419998
 2022-03-29  52.759998  52.531200  52.730000  52.650002    2684.0  52.650002

 [1059 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2013-06-04  25.110001  24.799999  25.100000  24.879999   59500.0  23.274130
 2013-06-05  25.070000  24.559999  25.070000  24.600000   19400.0  23.012205
 2013-06-06  24.740000  24.500000  24.740000  24.680000   31800.0  23.087038
 2013-06-07  25.320000  24.879999  25.320000  25.059999   26300.0  23.442511
 2013-06-10  26.260000  25.010000  25.600000  25.120001  582800.0  23.498642
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  59.590000  59.380001  59.590000  59.380001    5600.0  59.380001
 2022-03-24  60.040001  59.639999  59.639999  60.040001     400.0  60.040001
 2022-03-25  60.310001  60.020000  60.020000  60.310001     400.0  60.310001
 2022-03-28  60.139999  59.650002  59.650002  60.139999    3400.0  60.139999
 2022-03-29  61.061001  60.560001  60.560001  61.061001    3638.0  61.061001

 [2222 rows x 6 columns],
                  High        Low       Open      Close  Volume  Adj Close
 Date
 2016-07-20  25.780001  25.780001  25.780001  25.780001     0.0  19.205854
 2016-07-21  25.750000  25.750000  25.750000  25.750000  6600.0  19.183504
 2016-07-22  25.750000  25.750000  25.750000  25.750000     0.0  19.183504
 2016-07-25  25.740000  25.719999  25.740000  25.719999   500.0  19.161144
 2016-07-26  25.719999  25.719999  25.719999  25.719999     0.0  19.161144
 ...               ...        ...        ...        ...     ...        ...
 2022-03-23  39.040001  38.816002  39.040001  38.816002  1500.0  38.560204
 2022-03-24  39.150002  38.830002  38.830002  39.150002   300.0  38.892002
 2022-03-25  39.334999  38.930000  38.930000  39.334999   400.0  39.334999
 2022-03-28  39.118999  38.880001  38.959999  39.118999  8300.0  39.118999
 2022-03-29  39.660000  39.220001  39.660000  39.230000   660.0  39.230000

 [1434 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2012-03-21  20.070000  19.934999  19.955000  20.014999  123200.0  17.834314
 2012-03-22  19.955000  19.940001  19.940001  19.940001    1200.0  17.767490
 2012-03-23  19.920000  19.785000  19.785000  19.920000    8400.0  17.749668
 2012-03-26  20.230000  20.070000  20.070000  20.219999    2000.0  18.016977
 2012-03-27  20.260000  20.190001  20.260000  20.190001    4000.0  17.990255
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  76.669998  75.379997  76.209999  75.419998  289900.0  75.419998
 2022-03-24  76.750000  75.169998  75.580002  76.730003   43600.0  76.730003
 2022-03-25  76.889999  75.500000  76.889999  76.449997   40800.0  76.449997
 2022-03-28  77.519997  76.139999  76.559998  77.519997   24000.0  77.519997
 2022-03-29  79.040001  78.180000  78.489998  79.040001   26293.0  79.040001

 [2523 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2018-10-24  26.040001  24.510000  24.980000  24.510000  184200.0  23.630236
 2018-10-25  24.760000  24.500000  24.500000  24.650000   33800.0  23.765209
 2018-10-26  24.570000  24.170000  24.370001  24.260000   16400.0  23.389210
 2018-10-29  24.629999  23.950001  24.549999  23.950001  119000.0  23.090338
 2018-10-30  24.469999  24.420000  24.420000  24.450001     500.0  23.572392
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  44.919998  44.169998  44.919998  44.189999   80100.0  44.189999
 2022-03-24  44.689999  44.169998  44.439999  44.669998   63300.0  44.669998
 2022-03-25  44.930000  44.570000  44.930000  44.880001   50900.0  44.880001
 2022-03-28  44.959999  44.540001  44.810001  44.939999   89400.0  44.939999
 2022-03-29  45.450001  45.150002  45.320000  45.419998   51786.0  45.419998

 [863 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2016-09-15  25.299999  25.020000  25.145000  25.250000   15600.0  21.446877
 2016-09-16  25.370001  25.084999  25.370001  25.180000   14900.0  21.387419
 2016-09-19  25.350000  25.170000  25.209999  25.219999   18300.0  21.421389
 2016-09-20  28.600000  25.150000  25.240000  26.920000   52200.0  22.865347
 2016-09-21  25.459999  25.150000  25.270000  25.459999   59900.0  21.625244
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  44.240002  43.869999  44.160000  43.889999   86100.0  43.889999
 2022-03-24  44.400002  44.009998  44.110001  44.389999  124900.0  44.389999
 2022-03-25  44.730000  44.430000  44.490002  44.709999   49500.0  44.709999
 2022-03-28  44.830002  44.389999  44.650002  44.810001   84500.0  44.810001
 2022-03-29  45.310699  45.000500  45.189999  45.256901   52229.0  45.256901

 [1394 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2016-09-15  25.160000  24.865000  24.940001  25.150000    8800.0  20.508776
 2016-09-16  25.040001  24.870001  25.040001  24.995001    5700.0  20.382380
 2016-09-19  25.230000  25.080000  25.090000  25.120001   15700.0  20.484308
 2016-09-20  25.200001  25.059999  25.200001  25.059999    8600.0  20.435385
 2016-09-21  25.309999  25.070000  25.250000  25.280001    6000.0  20.614786
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  40.994999  40.750000  40.900002  40.750000  133300.0  40.750000
 2022-03-24  41.230000  40.807999  40.939999  41.209999  222200.0  41.209999
 2022-03-25  41.665001  41.310001  41.310001  41.660000  155800.0  41.660000
 2022-03-28  41.680000  41.320000  41.529999  41.680000  191200.0  41.680000
 2022-03-29  42.090000  41.770000  42.009998  42.070000  235405.0  42.070000

 [1394 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-09-15  25.129999  24.860001  24.870001  25.100000  14400.0  23.045485
 2016-09-16  24.992001  24.900000  24.990000  24.992001   2500.0  22.946323
 2016-09-19  25.125000  24.969999  25.080000  25.020000  10000.0  22.972029
 2016-09-20  25.299999  25.062000  25.299999  25.062000   7700.0  23.010590
 2016-09-21  25.299999  25.020000  25.160000  25.270000   6800.0  23.201565
 ...               ...        ...        ...        ...      ...        ...
 2022-03-23  49.400002  48.970001  49.400002  48.970001  21300.0  48.970001
 2022-03-24  49.480000  49.080002  49.080002  49.480000  19100.0  49.480000
 2022-03-25  49.869999  49.480000  49.540001  49.860001  20100.0  49.860001
 2022-03-28  50.139999  49.689999  49.720001  50.130001  43000.0  50.130001
 2022-03-29  50.644600  50.310001  50.400002  50.644600  44886.0  50.644600

 [1394 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-09-15  25.200001  24.860001  24.955000  25.180000   6200.0  23.739685
 2016-09-16  25.110001  25.010000  25.038000  25.049999  11500.0  23.617121
 2016-09-19  25.280001  25.160000  25.170000  25.165001   5500.0  23.725544
 2016-09-20  25.250000  25.150000  25.246000  25.150000   6500.0  23.711399
 2016-09-21  25.462000  25.145000  25.230000  25.462000  15200.0  24.005554
 ...               ...        ...        ...        ...      ...        ...
 2022-03-23  50.662998  50.060001  50.320000  50.110001   6900.0  50.110001
 2022-03-24  50.820000  50.209999  50.290001  50.820000   7800.0  50.820000
 2022-03-25  50.990002  50.685001  50.900002  50.950001  14800.0  50.950001
 2022-03-28  51.470001  50.799999  50.900002  51.470001  15600.0  51.470001
 2022-03-29  52.242802  51.882900  51.919998  52.223099   9506.0  52.223099

 [1394 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-09-16  25.205000  25.120001  25.180000  25.205000   5200.0  23.153015
 2016-09-19  25.370001  25.230000  25.320000  25.260000   8400.0  23.203541
 2016-09-20  25.510000  25.295000  25.510000  25.299999   7400.0  23.240280
 2016-09-21  25.549999  25.260000  25.400000  25.549999  10500.0  23.469925
 2016-09-22  25.860001  25.680000  25.860001  25.740000  10900.0  23.644461
 ...               ...        ...        ...        ...      ...        ...
 2022-03-23  51.939999  51.368999  51.939999  51.368999  23600.0  51.368999
 2022-03-24  52.145000  51.529999  51.549999  52.130001  18200.0  52.130001
 2022-03-25  52.450001  51.855000  52.450001  52.340000  36600.0  52.340000
 2022-03-28  52.680000  51.980000  52.380001  52.680000  46300.0  52.680000
 2022-03-29  53.279999  52.928699  53.000000  53.269600  41401.0  53.269600

 [1393 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-09-15  25.270000  24.940001  25.000000  25.260000   4200.0  22.872295
 2016-09-16  25.139999  25.049999  25.129999  25.049999   6000.0  22.682148
 2016-09-19  25.299999  25.120001  25.250000  25.129999  11700.0  22.754578
 2016-09-20  25.219999  25.100000  25.173000  25.150000   9500.0  22.772690
 2016-09-21  25.290001  25.100000  25.260000  25.290001  36800.0  22.899458
 ...               ...        ...        ...        ...      ...        ...
 2022-03-23  50.939999  50.439999  50.860001  50.439999  57500.0  50.439999
 2022-03-24  51.099998  50.529999  50.669998  51.080002  42600.0  51.080002
 2022-03-25  51.470001  51.000000  51.259998  51.470001  45100.0  51.470001
 2022-03-28  51.450001  50.930000  51.150002  51.402000  30300.0  51.402000
 2022-03-29  52.025002  51.665001  51.910000  52.020000  59214.0  52.020000

 [1394 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2006-07-11  19.940001  19.700001  19.799999  19.940001  248300.0  15.868084
 2006-07-12  19.889999  19.709999  19.889999  19.709999   11900.0  15.685054
 2006-07-13  19.660000  19.400000  19.660000  19.410000   13500.0  15.446314
 2006-07-14  19.540001  19.309999  19.540001  19.440001   19200.0  15.470189
 2006-07-17  19.360001  19.260000  19.360001  19.260000    3600.0  15.326948
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  77.849998  76.930000  77.830002  76.940002  342900.0  76.745865
 2022-03-24  77.680000  76.989998  77.250000  77.680000  326500.0  77.484001
 2022-03-25  78.000000  77.389999  77.779999  77.970001  331200.0  77.970001
 2022-03-28  78.290001  77.639999  78.139999  78.290001  272800.0  78.290001
 2022-03-29  79.167900  78.559998  78.970001  78.980003  318032.0  78.980003

 [3958 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2007-05-10  20.070000  20.030001  20.070000  20.040001    3000.0  17.857107
 2007-05-11  20.040001  20.040001  20.040001  20.040001       0.0  17.857107
 2007-05-14  20.040001  20.040001  20.040001  20.040001       0.0  17.857107
 2007-05-15  19.799999  19.799999  19.799999  19.799999     200.0  17.643250
 2007-05-16  19.799999  19.799999  19.799999  19.799999       0.0  17.643250
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  56.020000  55.009998  56.020000  55.029999  306500.0  54.954559
 2022-03-24  55.480000  54.900002  55.299999  55.439999  120300.0  55.363998
 2022-03-25  55.560001  54.900002  55.560001  55.270000   86800.0  55.270000
 2022-03-28  55.330002  54.599998  55.240002  55.299999  162800.0  55.299999
 2022-03-29  57.154999  56.279999  56.119999  57.154999  106069.0  57.154999

 [3749 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2007-05-10  19.840000  19.809999  19.830000  19.809999    3200.0  15.974217
 2007-05-11  19.780001  19.740000  19.740000  19.780001   10000.0  15.950023
 2007-05-14  19.820000  19.820000  19.820000  19.820000   12000.0  15.982276
 2007-05-15  19.780001  19.719999  19.780001  19.780001   11500.0  15.950023
 2007-05-16  19.780001  19.760000  19.780001  19.760000   11000.0  15.933893
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  63.270000  62.639999  63.090000  62.700001   37000.0  62.501583
 2022-03-24  63.200001  62.759998  63.060001  63.200001   33400.0  63.000004
 2022-03-25  63.750000  63.180000  63.180000  63.750000   65600.0  63.750000
 2022-03-28  63.860001  63.250000  63.860001  63.610001   19800.0  63.610001
 2022-03-29  63.720001  63.230000  63.869999  63.570000  214433.0  63.570000

 [3749 rows x 6 columns],
                  High        Low       Open      Close  Volume  Adj Close
 Date
 2017-01-04  24.061001  24.061001  24.061001  24.061001   600.0  23.023294
 2017-01-05  24.061001  24.061001  24.061001  24.061001     0.0  23.023294
 2017-01-06  24.061001  24.061001  24.061001  24.061001     0.0  23.023294
 2017-01-09  24.061001  24.061001  24.061001  24.061001     0.0  23.023294
 2017-01-10  24.061001  24.061001  24.061001  24.061001     0.0  23.023294
 ...               ...        ...        ...        ...     ...        ...
 2022-03-23  33.000000  32.990002  33.000000  32.990002   600.0  32.919304
 2022-03-24  33.224998  33.131001  33.224998  33.131001  1700.0  33.060001
 2022-03-25  33.306999  33.189999  33.189999  33.306999   500.0  33.306999
 2022-03-28  33.717999  33.410000  33.410000  33.717999  4700.0  33.717999
 2022-03-29  34.049999  33.840000  33.840000  34.049999  2665.0  34.049999

 [1318 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2016-03-18  20.120001  20.080000  20.090000  20.090000  12300.0  19.464140
 2016-03-21  20.090000  20.090000  20.090000  20.090000      0.0  19.464140
 2016-03-22  20.129999  20.049999  20.100000  20.100000  14800.0  19.473833
 2016-03-23  20.070000  20.037001  20.070000  20.037001  39100.0  19.412794
 2016-03-24  20.030001  19.959999  19.980000  20.030001  75600.0  19.406013
 ...               ...        ...        ...        ...      ...        ...
 2022-03-23  36.990002  36.750000  36.909000  36.854000   9100.0  36.788437
 2022-03-24  37.099998  36.900002  36.979000  37.099998  12700.0  37.034000
 2022-03-25  37.410000  36.959999  36.990002  37.410000   8700.0  37.410000
 2022-03-28  36.950001  36.720001  36.941002  36.950001  10800.0  36.950001
 2022-03-29  37.227402  36.570099  36.860001  37.227402   6725.0  37.227402

 [1519 rows x 6 columns],
                  High        Low       Open      Close    Volume  Adj Close
 Date
 2014-03-06  20.129999  19.864000  20.090000  19.864000  926500.0  19.273239
 2014-03-07  20.090000  19.700001  20.090000  19.860001  499400.0  19.269361
 2014-03-10  19.860001  19.680000  19.860001  19.820000  222000.0  19.230549
 2014-03-11  20.490000  19.620001  20.490000  19.670000  306800.0  19.085012
 2014-03-12  19.740000  19.490000  19.639999  19.690001  162000.0  19.104414
 ...               ...        ...        ...        ...       ...        ...
 2022-03-23  48.381001  47.820000  48.029999  47.840000  397500.0  47.755795
 2022-03-24  48.349998  47.990002  48.160000  48.290001  260300.0  48.205002
 2022-03-25  48.840000  48.209999  48.250000  48.840000  170300.0  48.840000
 2022-03-28  48.450001  47.840000  48.220001  48.200001   92400.0  48.200001
 2022-03-29  48.500000  47.687698  48.029999  48.500000  103236.0  48.500000

 [2032 rows x 6 columns],
                  High        Low       Open      Close  Volume  Adj Close
 Date
 2018-10-18  19.000000  18.290001  19.000000  18.350000  4600.0  17.419945
 2018-10-19  18.420000  18.280001  18.420000  18.280001  3600.0  17.353491
 2018-10-22  18.170000  18.129999  18.170000  18.129999  2100.0  17.211096
 2018-10-23  17.860001  17.610001  17.840000  17.860001  1000.0  16.954779
 2018-10-24  17.530001  17.500000  17.530001  17.520000   900.0  16.632011
 ...               ...        ...        ...        ...     ...        ...
 2022-03-23  26.209999  26.030001  26.209999  26.030001  4800.0  25.952271
 2022-03-24  26.160000  26.120001  26.139999  26.120001  2600.0  26.042002
 2022-03-25  26.250000  26.100000  26.100000  26.160000  6100.0  26.160000
 2022-03-28  26.070000  25.930000  25.930000  26.070000   600.0  26.070000
 2022-03-29  26.280001  26.070000  26.070000  26.280001  3034.0  26.280001

 [867 rows x 6 columns],
                  High        Low       Open      Close   Volume  Adj Close
 Date
 2017-08-09  19.959999  19.920000  19.920000  19.930000  10400.0  18.253019
 2017-08-10  19.830000  19.830000  19.830000  19.830000    300.0  18.161434
 2017-08-11  19.870001  19.796000  19.870001  19.796000   3000.0  18.130295
 2017-08-14  19.940001  19.940001  19.940001  19.940001    200.0  18.262175
 2017-08-15  19.940001  19.889999  19.889999  19.940001    300.0  18.262175
 ...               ...        ...        ...        ...      ...        ...
 2022-03-23  31.070000  30.820000  31.070000  30.820000   9600.0  30.675524
 2022-03-24  31.145000  30.850000  30.900000  31.145000   5800.0  30.999001
 2022-03-25  31.200001  31.030001  31.056999  31.159000  17400.0  31.159000
 2022-03-28  31.240000  31.009001  31.030001  31.240000   7000.0  31.240000
 2022-03-29  31.491699  31.329000  31.580000  31.491699   8183.0  31.491699

 [1168 rows x 6 columns],

In [8]:
etf_prices=pd.concat([etf.iloc[:,-1] for etf in etfs],axis=1)

In [9]:
etf_prices.columns=tickers
etf_prices

,SPDV,SDOG,VALQ,BFOR,ESGS,QQQE,DSTL,FDRR,FDVV,FDLO,...,DON,EZM,USMF,DGRW,DES,EES,DGRS,DTD,QARP,DEUS
Date,,,,,,,,,,,,,,,,,,,,,
2002-12-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-23,31.502001,54.365002,51.380001,59.380001,38.560204,75.419998,44.189999,43.889999,40.750000,48.970001,...,43.875793,54.426521,40.702045,62.666599,31.560577,48.070000,44.530609,63.816441,41.308998,45.060001
2022-03-24,31.730000,54.930000,52.020000,60.040001,38.892002,76.730003,44.669998,44.389999,41.209999,49.480000,...,44.244999,55.005001,41.044998,63.364998,31.790001,48.389999,44.690002,64.415001,41.853001,45.583000
2022-03-25,32.200001,55.650002,52.500000,60.310001,39.334999,76.449997,44.880001,44.709999,41.660000,49.860001,...,44.779999,55.410000,41.389999,63.740002,32.200001,48.570000,45.090000,65.000000,42.048000,45.891998
2022-03-28,31.962000,55.349998,52.419998,60.139999,39.118999,77.519997,44.939999,44.810001,41.680000,50.130001,...,44.650002,55.270000,41.271000,63.900002,32.020000,48.380001,44.840000,64.949997,42.234001,45.951000
2022-03-29,32.198101,55.810001,52.650002,61.061001,39.230000,79.040001,45.419998,45.256901,42.070000,50.644600,...,45.243698,56.264999,41.650002,64.510002,32.560001,49.380001,45.669998,65.448997,NaN,46.669998

In [10]:
etf_prices.to_csv("/Users/alexandra/Documents/master_thesis/etfs_prices_d.csv")

'''Resampling monthly prices'''
etf_prices = etf_prices.resample('BM').last()
etf_prices=etf_prices[0:-3]
etf_prices

,SPDV,SDOG,VALQ,BFOR,ESGS,QQQE,DSTL,FDRR,FDVV,FDLO,...,DON,EZM,USMF,DGRW,DES,EES,DGRS,DTD,QARP,DEUS
Date,,,,,,,,,,,,,,,,,,,,,
2002-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,29.801525,51.452648,51.364590,60.514904,36.052258,84.116852,42.624592,42.583046,37.841270,49.636444,...,42.250175,53.318699,40.317577,61.643162,31.374804,48.653183,45.330906,60.845604,41.407055,45.833542
2021-09-30,29.170265,50.091492,48.717285,58.410587,35.029278,80.043945,40.711021,40.911243,36.500305,47.363800,...,41.020248,51.736572,38.646835,58.307835,30.410513,47.854038,43.793938,58.107292,39.329845,43.751205
2021-10-29,29.473372,51.130775,50.226521,62.136181,36.477844,84.312706,43.076557,42.960754,38.433834,50.373871,...,42.869919,53.994637,40.248352,61.801361,31.524750,49.705624,45.352863,61.413269,41.696068,46.310684
2021-11-30,28.627098,49.464001,49.705204,61.888470,35.324505,82.960609,42.430508,42.354702,37.782745,49.382141,...,41.923954,52.999897,39.142284,61.427490,30.941048,49.269955,44.670940,60.558273,41.478790,45.286892
2021-12-31,30.739653,53.067764,52.938999,64.440002,37.947269,85.309998,46.153385,45.059345,39.963589,52.142040,...,44.239353,56.132027,41.843567,65.614792,32.756851,51.400002,47.377384,64.497055,43.751568,48.172531

In [11]:
'''Save adjusted close prices'''
etf_prices.to_csv("/Users/alexandra/Documents/master_thesis/etfs_prices.csv")

In [4]:
'''Download and save S&P 500 historical values'''
sp500=YahooDailyReader('^GSPC', start=datetime.date(2002, 12, 1),interval='d').read()
sp500=sp500['Adj Close']
sp500.to_csv("/Users/alexandra/Documents/master_thesis/sp500_d.csv")

In [3]:
sp500=YahooDailyReader('^GSPC', start=datetime.date(2002, 12, 1),interval='m').read()
sp500=sp500['Adj Close']
sp500=sp500[:-4]
sp500.to_csv("/Users/alexandra/Documents/master_thesis/sp500.csv")